### ISSUE TITLE
[Prose] right side menu in authorization server is wrong

### ISSUE THREAD

**Issue by yuliu-okta** [okta/okta-developer-docs#1017]
go to https://developer.okta.com/docs/reference/api/authorization-servers/, the menu on the right side is wrong.

**Comment by alexdahl-okta** [comment]
Interesting.

The content nav extracts the headings from the article content. At a glance, looks like the article heading structure is wrong – the first `Authorization Server operations` section is an `h3` instead of an `h2`, etc.

Looks like the [markdown source](https://github.com/okta/okta-developer-docs/blob/master/packages/%40okta/vuepress-site/docs/reference/api/authorization-servers/index.md) has been that way for a while. Updated headings should get the content nav to show what we want.

**Comment by alexdahl-okta** [comment]
Related: #328.

**Comment by dogeared** [comment]
Moved to: https://oktainc.atlassian.net/browse/OKTA-365103
