### ISSUE TITLE
On Node Express "Next Steps" link directly to correct Node.js documentation

### ISSUE THREAD

**Issue by reverentgeek** [okta/okta-developer-docs#1409]
On the [Next steps](https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/next-steps/) the **Protect your API endpoints** link should go directly to the [Express-specific guide](https://developer.okta.com/docs/guides/protect-your-api/nodeexpress/before-you-begin/).

**Comment by mraible** [comment]
@reverentgeek I agree that's how things should work. However, it seems that the links on the top don't match the selected framework on the bottom. @jakubvul Is this something we can fix?

**Comment by robertjd** [comment]
@mraible not sure what you mean by not matching?

We also link out to the sample application the first step of the guide ([see here](https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/before-you-begin/)), so I don't think we need to surface these again at the end of the guide.

**Comment by mraible** [comment]
@robertjd If you go to https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/next-steps/. It'll have **Node Express** selected in the Sample Applications section. If you click on the **Protect Your API Endpoints** link (https://developer.okta.com/docs/guides/protect-your-api/), it goes to https://developer.okta.com/docs/guides/protect-your-api/aspnet/before-you-begin/ and **ASP.NET** is selected, instead of **Node Express**.

**Comment by dogeared** [comment]
moved to: https://oktainc.atlassian.net/browse/OKTA-368658
