### ISSUE TITLE
customize-tokens-groups-claim guide missing key step found in support

### ISSUE THREAD

**Issue by gregparsons** [okta/okta-developer-docs#3310]
Thank you for getting involved with Okta's Developer Docs!

> Note: If you are an Okta employee, please [clone this Jira](https://oktainc.atlassian.net/browse/OKTA-250417) instead of opening a GitHub issue.

Please provide the following information so that we can act on your feedback.

**Affected page(s):**
https://developer.okta.com/docs/guides/customize-tokens-groups-claim/main/

**Describe the problem(s):**
Does not include this information which is pretty critical to scenario actually working on a default auth server:
https://support.okta.com/help/s/question/0D54z00007JYLaqCAH/one-or-more-scopes-are-not-configured-for-the-authorization-server-resource?language=en_US

**If possible, describe a proposed fix:**
Don't caveat that this procedure is only required for a custom server. I could totally be wrong if I previously deleted "groups" in my security/api settings on my default auth server. In which case, promptly delete this. Or maybe mention that it needs to be manually filled in if historically someone changed it. Thanks!

We will do our best to respond to you within 2 working days.

**Comment by brianduffield-okta** [comment]
Thanks for the feedback, @gregparsons ! Created an internal JIRA ticket to track this issue: [OKTA-494626](https://oktainc.atlassian.net/browse/OKTA-495626).

**Comment by susanharper-okta** [comment]
@gregparsons - I have a question to clarify exactly what your issue is so that I can troubleshoot:

Are you attempting to add a Groups claim to the Okta Org Authorization Server or a Custom Authorization Server? The default auth server is a custom authorization server. So, if you are following those steps, when you go to Security > API and select the **default** authorization server, are you attempting to select **Groups** from the **Value type** dropdown menu and it isn't there as an option?

<img width="683" alt="issue" src="https://user-images.githubusercontent.com/45509385/168340927-5ceba9e6-0590-4881-8430-6c1846025171.png">

Thank you, in advance, for the clarification. :)
