### ISSUE TITLE
How to redirect to originally requested URL after login?

### ISSUE THREAD

**Issue by anydoby** [okta/okta-developer-docs#3747]
Dear okta devs, thanks for the awesome examples on integrating okta auth using different languages. I have followed an example for `node` and missing one important thing. The example authentication callback simply redirects every logged in user to the `/profile` page:

      app.use('/authorization-code/callback',
        passport.authenticate('oidc', { failureRedirect: '/error' }),
        (req, res) => {
          res.redirect('/profile');
        }
      );

I have not found any way to redirect to the originally requested URL though. I've done integration with spring-boot and don't remember any issues with that. It just worked to the URL that the user entered in the browser, after successful login. For node I assume I have to write some magic. Is this correct?

**Comment by brianduffield-okta** [comment]
Thanks for the feedback, @anydoby Let me check with my colleagues to get an answer for you.

**Comment by brianduffield-okta** [comment]
@anydoby One of our developer advocates provided the following guidance:

The general pattern is to remember the page the user was on before redirecting to Okta (store the value in the session), and then, after the user signs-in successfully, check if the previous page is in session for the redirection to that page. Otherwise, it falls back to another page (for example, `/profile`).

Let me know if you need more info.

**Comment by anydoby** [comment]
Hi @brianduffield-okta thanks for the quick and complete answer. I got the idea. We were considering what to use for our little service that needs Okta protection and will go for the springboot version as it seems more is handled out of the box by spring than the bare bones nodejs+express.
