### ISSUE TITLE
Items Missing from Authentication Guide TOC on the left and API Concepts items not alpha

### ISSUE THREAD

**Issue by susanharper-okta** [okta/okta-developer-docs#69]
The TOC is missing several items - including social IdPs and the new Generic OIDC IdP.

Also, lower on the page - the API Concepts topics aren't in alpha order for some reason.

Old Site

<img width="754" alt="oldsite" src="https://user-images.githubusercontent.com/45509385/54834336-94a95f00-4c85-11e9-9df8-a82a841f95c1.png">

Vuepress
<img width="717" alt="vuepress" src="https://user-images.githubusercontent.com/45509385/54834348-9a06a980-4c85-11e9-83c4-4ced38493764.png">

**Comment by bretterer** [comment]
This will require some rebuilding.  Right now, the nav is being built from the content of `/documentation/` because at the time, they mirrored each other.  It appears we now want different items on the sidebar from what is on `/documentation/`

I will update this to be explicit in `.vuepress/config.js` to define this menu
